#!/bin/bash
sudo pacman -Syu
sudo pacman -S git
git config --global user.email "a.mo.dewidar@gmail.com"
git config --global user.name "Ahmed Dewidar"
sudo pacman -S chromium
sed -i 's/palemoon/chromium/g' ~/.profile
sed -i 's/"Pale Moon"/chromium/g' ~/.config/mimeapps.list
sudo cp 50-mouse-acceleration.conf /etc/X11/xorg.conf.d/
sudo pacman -R palemoon-bin
sudo pacman -S thunderbird
sudo pacman -S zsh
chsh -s $(which zsh)
