#!/bin/bash
sudo pacman -Syu
sudo pacman -S git
sudo pacman -S nautilus
sudo pacman -S chromium
sed -i 's/palemoon/chromium/g' ~/.profile
sed -i 's/Pale Moon/chromium/g' ~/.config/mimeapps.list
sudo pacman -R palemoon-bin
sudo pacman -S termite
echo "export TERMINAL=/usr/bin/termite" >> ~/.profile
sudo pacman -S code
sudo pacman -S zsh
chsh -s $(which zsh)
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

## Uncomment this if you remembered what it does
#echo "options snd_hda_intel index=1" | sudo tee -a /etc/modprobe.d/alsa-base.conf